spring.datasource.url=jdbc:postgresql://localhost:5436/api_documentation
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET:VGhpc0lzQURldk9ubHlTZWNyZXRLZXlGb3JBcGlEb2N1bWVudGF0aW9uMjAyNg==}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
